//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rieltor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Договора
    {
        public int Код { get; set; }
        public string НомерДоговора { get; set; }
        public System.DateTime ДатаЗаключения { get; set; }
        public string Статус { get; set; }
        public Nullable<int> КлиентID { get; set; }
        public Nullable<int> СоздательID { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
